---
driver:
  name: dokken
  privileged: true
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: amazonlinux-2
    driver:
      image: dokken/amazonlinux-2
  - name: centos-7
    driver:
      image: dokken/centos-7
  - name: debian-10
    driver:
      image: dokken/debian-10
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
