---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  
platforms:
  - name: amazonlinux-2
  - name: centos-7
  - name: debian-9
  - name: ubuntu-18.04

suites:
  - name: default
    run_list: test::default
    verifier:
      inspec_tests:
        - test/integration/default
  - name: custom_resource
    run_list: test::custom_resource
    verifier:
      inspec_tests:
        - test/integration/custom_resource
