name: Test on supported platforms

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ 'amazonlinux-2', 'centos-7', 'debian-10', 'ubuntu-2004' ]
    steps:
    - uses: actions/checkout@master
    - name: Install Chef Workstation
      run: |
        wget -qO - https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chef-workstation -s once
        chef --version
    - name: Verify Docker installation
      run: docker version
    - name: Run tests
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      run: |
        eval "$(chef shell-init bash)"
        kitchen test ${{ matrix.platform }}
